<template>
  <v-dialog
    :value="visible"
    max-width="360"
    persistent
    @input="close"
  >
    <v-layout
      align-center
      justify-center
    >
      <v-flex xs12>
        <v-card class="elevation-12">
          <v-toolbar dark>
            <v-toolbar-title>{{ $t('forms.routeSheet.title') }}</v-toolbar-title>
            <v-spacer/>
          </v-toolbar>
          <v-card-text>
            <v-form autocomplete="off"
                    @keyup.native.enter="save"
            >
              <v-text-field v-show="false"
                            v-model="item.autogenerated"
                            type="hidden"
              />
              <CompanySelect v-validate="'required'"
                             v-model="item.company_id"
                             :readonly="itemExists || !formEditable"
                             :error-messages="errors.collect('company_id')"
                             :data-vv-as="$t('routeSheet.fields.company.name')"
                             :clearable="false"
                             name="company_id"
              />
              <RouteSelect v-validate="''"
                           v-model="item.route_id"
                           :company-id="item.company_id"
                           :error-messages="errors.collect('route_id')"
                           :data-vv-as="$t('routeSheet.fields.route.name')"
                           :readonly="!formEditable"
                           name="route_id"
              />
              <BusSelect v-validate="'required'"
                         v-model="item.bus_id"
                         :company-id="item.company_id"
                         :error-messages="errors.collect('bus_id')"
                         :data-vv-as="$t('routeSheet.fields.bus.state_number')"
                         :readonly="!formEditable"
                         name="bus_id"
              />
              <DriverSelect v-validate="''"
                            v-model="item.driver_id"
                            :company-id="item.company_id"
                            :error-messages="errors.collect('driver_id')"
                            :data-vv-as="$t('routeSheet.fields.driver.full_name')"
                            :readonly="!formEditable"
                            name="driver_id"
              />
              <v-layout row>
                <v-flex xs7>
                  <DateSelect v-validate="'required'"
                              v-model="item.active_from"
                              :label="$t('routeSheet.fields.active_from')"
                              :error-messages="errors.collect('active_from')"
                              :data-vv-as="$t('routeSheet.fields.active_from')"
                              :readonly="!formEditable"
                              name="active_from"
                  />
                </v-flex>
                <v-flex xs4
                        class="pl-2"
                >
                  <v-text-field v-validate="'required'"
                                v-model="active_from_time"
                                :readonly="!Boolean(item.active_from) || !formEditable"
                                :error-messages="errors.collect('active_from_time')"
                                :data-vv-as="$t('routeSheet.fields.active_from')"
                                append-icon="access_time"
                                type="time"
                                step="1"
                                name="active_from_time"
                                @change="handleActiveFromTime"
                  />
                </v-flex>
              </v-layout>
              <v-layout row>
                <v-flex xs7>
                  <DateSelect v-validate="'required'"
                              v-model="item.active_to"
                              :label="$t('routeSheet.fields.active_to')"
                              :error-messages="errors.collect('active_to')"
                              :data-vv-as="$t('routeSheet.fields.active_to')"
                              :clearable="true"
                              :readonly="!formEditable"
                              name="active_to"
                  />
                </v-flex>
                <v-flex xs4
                        class="pl-2"
                >
                  <v-text-field v-validate="'required'"
                                v-model="active_to_time"
                                :readonly="!Boolean(item.active_to) || !formEditable"
                                :error-messages="errors.collect('active_to_time')"
                                :data-vv-as="$t('routeSheet.fields.active_to')"
                                append-icon="access_time"
                                type="time"
                                step="1"
                                name="active_to_time"
                                @change="handleActiveToTime"
                  />
                </v-flex>
              </v-layout>
            </v-form>
          </v-card-text>
          <v-card-actions>
            <v-layout row
                      wrap
                      justify-end
            >
              <v-spacer/>
              <v-btn color="default"
                     @click="close"
              >
                {{ $t('common.buttons.close') }}
              </v-btn>
              <v-btn v-if="formSubmittable"
                     :loading="inProgress"
                     color="primary"
                     @click="save"
              >
                {{ $t('common.buttons.save') }}
              </v-btn>
            </v-layout>
          </v-card-actions>
        </v-card>
      </v-flex>
    </v-layout>
  </v-dialog>
</template>

<script>
import moment from 'moment';
import RouteSheetsService from '../../services/RouteSheetsService';
import FormValidationMixin from '../../mixins/FormValidationMixin';
import CompanySelect from '../dropdowns/CompanySelect';
import RoleSelect from '../dropdowns/RoleSelect';
import ModalFormMixin from '../../mixins/ModalFormMixin';
import RouteSelect from '../dropdowns/RouteSelect';
import EntityFormMixin from '../../mixins/EntityFormMixin';
import BusSelect from '../dropdowns/BusSelect';
import DriverSelect from '../dropdowns/DriverSelect';
import DateSelect from '../dropdowns/DateSelect';
import PoliciesService from '../../services/PoliciesService';

export default {
  name:       'RouteSheetForm',
  components: {
    DateSelect,
    DriverSelect,
    BusSelect,
    RouteSelect,
    RoleSelect,
    CompanySelect,
  },
  mixins: [
    ModalFormMixin,
    FormValidationMixin,
    EntityFormMixin,
  ],
  data() {
    return {
      active_to_time:   null,
      active_from_time: null,
      emptyTime:        '00:00:00',
      item:             {
        id:            null,
        company_id:    null,
        route_id:      null,
        bus_id:        null,
        driver_id:     null,
        active_from:   null,
        active_to:     null,
        autogenerated: null,
      },
      service:  RouteSheetsService,
      itemType: PoliciesService.itemsTypes.routeSheets,
    };
  },
  watch: {
    value: {
      deep: true,
      handler(newValue) {
        this.item = Object.assign({}, newValue, { autogenerated: false });
      },
    },
    item: {
      deep: true,
      handler(newValue) {
        this.active_from_time = this.getTime(newValue.active_from);
        this.active_to_time = this.getTime(newValue.active_to);
      },
    },
  },
  methods: {
    handleActiveToTime(newValue) {
      this.active_to_time = newValue || this.emptyTime;

      if (!this.item.active_to) {
        return;
      }

      this.item.active_to = this.setTime(this.item.active_to, this.active_to_time);
    },
    handleActiveFromTime(newValue) {
      this.active_from_time = newValue || this.emptyTime;

      if (!this.item.active_from) {
        return;
      }

      this.item.active_from = this.setTime(this.item.active_from, this.active_from_time);
    },
    /**
     * Extracts time part from date.
     *
     * @param {Date} date Date to extract time from
     * @return {string|null} Time string
     */
    getTime(date) {
      if (date) {
        return moment(date).format('HH:mm:ss');
      }

      return null;
    },
    /**
     * Sets time part of date.
     *
     * @param {Date} date Date to set time in
     * @param {string} timeString Time to set
     *
     * @return {string} Date with new time
     */
    setTime(date, timeString) {
      const [ hours, minutes, seconds ] = timeString.split(':');

      return moment(date)
        .minutes(Number.parseInt(minutes, 10))
        .hour(Number.parseInt(hours, 10))
        .second(Number.parseInt(seconds, 10))
        .utc(false)
        .format();
    },
  },
};
</script>
