<?php

return [
    'id' => 'ID',
    'company.name' => 'Компания',
    'route.name' => 'Маршрут',
    'bus.state_number' => 'Автобус',
    'driver.full_name' => 'Водитель',
    'active_from' => 'Действует с',
    'active_to' => 'Действует по',
    'autogenerated' => 'Автоматический',
    'transactions_count' => 'Транзакций',
];
